version: "3.8"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}