FROM node:22-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run prisma:generate:dev
RUN npm run prisma:dbsync:dev
CMD ["npm", "run", "start:dev"]