version: '3.8'
services:
  redis:
    image: 'redis:7-alpine'
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}