version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}