name: Deploy main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner OS
        run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.AWS_APP_NAME }}:latest ./
      - name: Build Nginx image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx ./nginx
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.AWS_APP_NAME }}:latest
      - name: Push Nginx image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_APP_NAME }}-env
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
